name: GitHub Actions Build and Deploy Demo        # 大标题
on:
  push:
    branches:
      - master                                   # 监听哪个分支的哪个动作
permissions:
  contents: write                                # 设置权限，可写，也可以不用配置，v4版本新增的
jobs:
  build-and-deploy:                              # 其中一个任务的名称，ID
    runs-on: ubuntu-latest                       # 这个任务运行所需的环境
    steps:
      - name: Checkout                           # 第一步：获取源码
        uses: actions/checkout@v3                # 使用的工具
  <span class="token operator">-</span> name<span class="token operator">:</span> Install and Build                  # 第二步：下载依赖和构建
    <span class="token literal-property property">run</span><span class="token operator">:</span> <span class="token operator">|</span>
      npm install
      npm run build

  <span class="token operator">-</span> name<span class="token operator">:</span> Deploy                           # 第三步：部署
    <span class="token literal-property property">uses</span><span class="token operator">:</span> JamesIves<span class="token operator">/</span>github<span class="token operator">-</span>pages<span class="token operator">-</span>deploy<span class="token operator">-</span>action@v4
    <span class="token keyword">with</span><span class="token operator">:</span>
      <span class="token literal-property property">folder</span><span class="token operator">:</span> dist                         # 部署的目录
      <span class="token literal-property property">branch</span><span class="token operator">:</span> deploy                       # 部署到哪个分支
